products/ui/llbuildui/__init__.py
__author__ = 'Daniel Dunbar'
__email__ = 'daniel@zuster.org'
__versioninfo__ = (0, 1, 0)
__version__ = '.'.join(map(str, __versioninfo__)) + 'dev'

__all__ = []

products/ui/llbuildui/app.py
import os

import flask

import database
import trace
import views

class LLBuildApp(flask.Flask):
    def __init__(self, name):
        super(LLBuildApp, self).__init__(name)

        # Register the local proxy.
        
        # Register the teardown functions.
        @self.teardown_appcontext
        def _teardown(exception):
            db = flask.g.get('_database_session', None)
            if db is not None:
                db.close()

        self.register_blueprint(views.main)

    @property
    def trace(self):
        d = flask.g.get('_trace', None)
        if d is None:
            result = trace.Trace.frompath(flask.session["trace"])
            d = flask.g._trace = result
        return d

    @property
    def database_session(self):
        s = flask.g.get('_database_session', None)
        if s is None:
            # This session will be closed by the teardown function we register.
            db = database.Database.get_database(flask.session["db"])
            s = flask.g._database_session = db.session_factory()
        return s

app = LLBuildApp(__name__)

# Set the secret key.
#
# We never expect this app to persist, so we just assign a new one each time.
app.secret_key = "DEBUG" if app.debug else os.urandom(24)

products/ui/llbuildui/views.py
import flask
import sqlalchemy.sql
import sqlalchemy.sql.expression

from flask import Flask, current_app, g, redirect, request, session, url_for

import graphalgorithms
import model

main = flask.Blueprint('main', __name__)

@main.route('/')
def index():
    return flask.render_template("index.html")

# MARK: Trace Viewer

@main.route('/trace')
def trace_root():
    # If no database has been selected, prompt for one.
    trace_path = session.get("trace")
    if trace_path is None:
        return redirect(url_for('main.trace_config'))
    
    return flask.render_template(
        "trace_root.html", trace=current_app.trace,
        trace_path=session.get("trace"))

@main.route('/trace/config', methods=['GET', 'POST'])
def trace_config():
    if request.method == 'POST':
        session['trace'] = request.form['trace_path']
        return redirect(url_for('main.trace_root'))
    return flask.render_template("trace_config.html",
                                 trace_path=session.get("trace"))

# MARK: Database Browser

@main.route('/db')
def db_root():
    # If no database has been selected, prompt for one.
    db_path = session.get("db")
    if db_path is None:
        return redirect(url_for('main.db_config'))
    
    s = current_app.database_session

    # Compute the roots of the results.
    #
    # We compute this by simply looking for nodes which have no dependencies.
    dependees = set()
    for result in s.query(model.RuleResult):
        for item in result.dependencies:
            dependees.add(item)
    roots = [result
             for result in s.query(model.RuleResult)
             if result.key_id not in dependees]

    return flask.render_template("db_root.html", db_path=db_path, roots=roots)

@main.route('/db/config', methods=['GET', 'POST'])
def db_config():
    if request.method == 'POST':
        session['db'] = request.form['db_path']
        return redirect(url_for('main.db_root'))
    return flask.render_template("db_config.html", db_path=session.get("db"))

@main.route('/db/diagnostics', methods=['GET', 'POST'])
def db_diagnostics():
    s = current_app.database_session

    # Find all the rules.
    rules = {}
    key_names = {}
    for result in s.query(model.KeyName):
        key_names[result.id] = result.name
    for result in s.query(model.RuleResult):
        rules[result.key_id] = result

    # Find information on any cycles in the database.
    def successors(id):
        # Get the rule.
        rule = rules[id]

        # Get the dependencies.
        succs = []
        for dependency in rule.dependencies:
            succs.append(dependency)
        return succs
    keys = sorted(rules.keys())
    cycle = graphalgorithms.find_cycle(keys, successors)
    if cycle is not None:
        cycle = cycle[0].items + [cycle[1]]
        cycle = [key_names[id] for id in cycle]
    
    return flask.render_template("db_diagnostics.html",
                                 db_path=session.get("db"),
                                 session=s, model=model, sql=sqlalchemy.sql,
                                 cycle=cycle)


# MARK: Model Object Views

@main.route('/db/rule_result/<path:name>')
def db_rule_result(name):
    # Get the result.
    s = current_app.database_session
    rule_result = s.query(model.RuleResult).join(model.KeyName).filter(
        model.KeyName.name == name).one()
    dependency_results = [
        s.query(model.RuleResult).filter_by(
            key_id=dependency).one()
        for dependency in rule_result.dependencies]
    # FIXME: We need to get back the dependents view, it was super useful.
    dependency_results = sorted(dependency_results, key=lambda d: d.key.name)
    
    return flask.render_template(
        "db_rule_result.html",
        db_path=session.get("db"), rule_result=rule_result,
        dependency_results=dependency_results)

products/ui/llbuildui/templates/config.html
{% extends "layout.html" %}
{% block title %}Configuration{% endblock %}
{% block body %}

        
Select the database:
<form action="" method="post">
  <p><input type=text name=db_path>
  <p><input type=submit value="Set Path">
</form>

{% endblock %}

products/ui/llbuildui/templates/db_config.html
{% extends "layout.html" %}
{% block title %}Configuration{% endblock %}
{% block body %}

        
Select the database:
<form action="" method="post">
  <p><input type=text name=db_path>
  <p><input type=submit value="Set Path">
</form>

{% endblock %}

products/ui/llbuildui/templates/db_diagnostics.html
{% extends "layout.html" %}
{% block title %}Database Diagnostics{% endblock %}
{% block body %}

<p>
  Key Names: {{ "{:,d}".format(session.query(model.KeyName).count()) }}<br/>
  Key Names Size: {{ "{:,d}".format(session.query(sql.functions.sum(sql.functions.char_length(model.KeyName.name))).first()[0]) }}<br/>
  Rule Results: {{ "{:,d}".format(session.query(model.RuleResult).count()) }}<br/>
  Rule Dependencies: {{ "{:,d}".format(session.query(model.RuleDependency).count()) }}<br/>
</p>

{% if cycle %}
<p>
  <font color="red">WARNING: Database contains a cycle!</font><br>
  <ul>
    {% for node in cycle %}
    <li>{{node}}</li>
    {% endfor %}
  </ul>
</p>
{% endif %}

{% endblock %}

products/ui/llbuildui/templates/db_root.html
{% extends "layout.html" %}
{% block title %}Root Node{% endblock %}
{% block body %}

<p>
  Roots:
  {% for root in roots %}
  <a href="{{ url_for('main.db_rule_result', name=root.key.name) }}">{{ root.key.name }}</a> (id: {{ root.id }})<br>
  {% endfor %}
</p>

{% endblock %}

products/ui/llbuildui/templates/db_rule_result.html
{% extends "layout.html" %}
{% block title %}Rule Result: {{ rule_result.key.name }} {% endblock %}
{% block body %}

<h4>Dependencies</h4>

{% for dependency in dependency_results %}
<a href="{{ url_for('main.db_rule_result', name=dependency.key.name) }}">
  {{ dependency.key.name }} (id: {{ dependency.id }})
</a><br>
{% endfor %}

<!-- FIXME: This view is not currently supported
<h4>Dependents</h4>

{% for dependent in dependents_results %}
<a href="{{ url_for('main.db_rule_result', name=dependent.key.name) }}">
  {{ dependent.key.name }} (id: {{ dependent.id }})
</a><br>
{% endfor %}
-->

<h4>Value</h4>
{{ rule_result.value }}

{% endblock %}

products/ui/llbuildui/templates/diagnostics.html
{% extends "layout.html" %}
{% block title %}Database Diagnostics{% endblock %}
{% block body %}

<p>
  Key Names: {{ "{:,d}".format(session.query(model.KeyName).count()) }}<br/>
  Key Names Size: {{ "{:,d}".format(session.query(sql.functions.sum(sql.functions.char_length(model.KeyName.name))).first()[0]) }}<br/>
  Rule Results: {{ "{:,d}".format(session.query(model.RuleResult).count()) }}<br/>
  Rule Dependencies: {{ "{:,d}".format(session.query(model.RuleDependency).count()) }}<br/>
</p>

{% if cycle %}
<p>
  <font color="red">WARNING: Database contains a cycle!</font><br>
  <ul>
    {% for node in cycle %}
    <li>{{node}}</li>
    {% endfor %}
  </ul>
</p>
{% endif %}

{% endblock %}

products/ui/llbuildui/templates/index.html
{% extends "layout.html" %}
{% block title %}llbuild Debugging UI{% endblock %}
{% block body %}

<p><a href="{{ url_for('main.trace_root') }}">Tracer Viewer</a></p>
<p><a href="{{ url_for('main.db_root') }}">Database Browser</a></p>

{% endblock %}

products/ui/llbuildui/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <link href="{{ url_for('static', filename='style.css') }}" rel="stylesheet">
  
  {% block head %} {% endblock %}
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="{{ url_for('main.index') }}">llbuild</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% if db_path %}
            <li><a href="{{ url_for('main.db_config') }}"><i>Database:</i> {{ db_path }}</a></li>
            {% endif %}
            {% if trace_path %}
            <li><a href="{{ url_for('main.trace_config') }}"><i>Trace:</i> {{ trace_path }}</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      <div class="page-header">
        <h1>{% block title %}{% endblock %}</h1>
      </div>
      <div class="row content">
        <div class="col-sm-8">
          {% block body %}{% endblock %}
        </div>
      </div>
    </div>

    </div><!-- /.container -->
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

products/ui/llbuildui/templates/rule_result.html
{% extends "layout.html" %}
{% block title %}Rule Result: {{ rule_result.key.name }} {% endblock %}
{% block body %}

<h4>Dependencies</h4>

{% for dependency in dependency_results %}
<a href="{{ url_for('main.rule_result', name=dependency.key.name) }}">
  {{ dependency.key.name }} (id: {{ dependency.id }})
</a><br>
{% endfor %}

<h4>Dependents</h4>

{% for dependent in dependents_results %}
<a href="{{ url_for('main.rule_result', name=dependent.key.name) }}">
  {{ dependent.key.name }} (id: {{ dependent.id }})
</a><br>
{% endfor %}

<h4>Value</h4>
{{ rule_result.value }}

{% endblock %}

products/ui/llbuildui/templates/trace_config.html
{% extends "layout.html" %}
{% block title %}Configuration{% endblock %}
{% block body %}

        
Select the trace path:
<form action="" method="post">
  <p><input type=text name=trace_path value="{{trace_path}}">
  <p><input type=submit value="Set Path">
</form>

{% endblock %}

products/ui/llbuildui/templates/trace_root.html
{% extends "layout.html" %}
{% block title %}Build Trace{% endblock %}
{% block body %}

<p>
  Events:<br>
  {% for event in trace.events%}
  {% if event.isReadiedTask %}
  {{event.task.rule.key}}<br><br>
  {% endif %}
  {% endfor %}
</p>

{% endblock %}